### ISSUE TITLE
pbs comment clearing

### ISSUE THREAD

**Issue by jtillots** [Will-Shanks/ctt_server#39] opened 2024-08-09 23:06 UTC
We need something to clear the comments when a node is returned to service. Otherwise, when a mom goes down, CTT will report whatever the PBS comment is which is often something really old. This is confusing to the on call. I suggest not pulling in the PBS comment at all and let the admin look at PBS to get that comment. That would be better than CTT showing a comment that is out-of-date. At best, maybe CTT can clear the PBS comment from a node when it notices it is back online.

**Comment by Will-Shanks** [comment] 2024-08-16 17:02
This was a regression caused by #30 but should be fixed as of [v0.3.6](https://github.com/NCAR/ctt_server/releases/tag/v0.3.6). CTT should be correctly clearing scheduler comments when it releases nodes so occurrences of this still happening are likely due to nodes resumed before the fix was implemented ~3 weeks ago.

**Closed as completed by Will-Shanks** 2024-08-16 17:02 UTC
